# -*- coding: utf-8 -*-
"""30jan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxwRUxfePFW0zLc8n-xzfsp6cp08wVGB

**Question 1**: Write a program to accept percentage from the user and display the grade according to the following criteria:

**Answer**
"""

# Program to display grade based on percentage
percentage = float(input("Enter your percentage: "))

if percentage > 90:
    grade = 'A'
elif 80 < percentage <= 90:
    grade = 'B'
elif 60 <= percentage <= 80:
    grade = 'C'
else:
    grade = 'D'

print(f"Your grade is: {grade}")

"""Question 2: Write a program to accept the cost price of a bike and display the road tax to be paid according to the following criteria:

**Answer :**
"""

# Program to calculate road tax
cost_price = float(input("Enter the cost price of the bike: "))

if cost_price > 100000:
    tax = 0.15 * cost_price
elif 50000 < cost_price <= 100000:
    tax = 0.10 * cost_price
else:
    tax = 0.05 * cost_price

print(f"The road tax to be paid is: Rs. {tax}")

"""Question 3: Accept any city from the user and display monuments of that city.

**Answer**:
"""

# Program to display monuments based on city
city = input("Enter the name of the city: ").strip().capitalize()

monuments = {
    "Delhi": "Red Fort",
    "Agra": "Taj Mahal",
    "Jaipur": "Jal Mahal"
}

if city in monuments:
    print(f"The monument in {city} is {monuments[city]}")
else:
    print("City not found in the database.")

"""Question 4: Check how many times a given number can be divided by 3 before it is less than or equal to 10.

**Answer**:
"""

# Program to count divisions by 3
number = int(input("Enter a number: "))
count = 0

while number > 10:
    number /= 3
    count += 1

print(f"The number can be divided by 3, {count} times before it is <= 10.")

"""Question 5: Why and When to Use While Loop in Python (give a detailed description with examples)

**Answer**:

**Why Use a While Loop:**
A while loop is used when the number of iterations is not known beforehand, and the loop continues until a specific condition is met. It is useful for situations where an action needs to be repeated based on a condition rather than a fixed number of times.

**When to Use a While Loop:**

To repeatedly execute a block of code as long as the condition is true.
When the loop termination depends on a condition that changes dynamically during runtime.

**Example:**
"""

# Example of a while loop
number = 5
while number > 0:
    print(number)
    number -= 1

"""Question 6: Use a nested while loop to print 3 different patterns.

**Answer**:
"""

# Nested while loop to print patterns
# Pattern 1
i = 1
print("Pattern 1:")
while i <= 5:
    print("*" * i)
    i += 1

# Pattern 2
print("\nPattern 2:")
i = 5
while i > 0:
    j = 0
    while j < i:
        print("*", end="")
        j += 1
    print()
    i -= 1

# Pattern 3
print("\nPattern 3:")
i = 1
while i <= 5:
    j = 5
    while j > i:
        print(" ", end="")
        j -= 1
    print("*" * i)
    i += 1

"""Question 7: Reverse a while loop to display numbers from 10 to 1.

**Answer:**
"""

# Program to display numbers from 10 to 1 using a while loop
number = 10
while number >= 1:
    print(number, end=" ")
    number -= 1
print()

"""Question 8: Reverse a while loop to display numbers from 10 to 1.

**Answer:**
"""

# Program to display numbers from 10 to 1 using a while loop
number = 10
while number >= 1:
    print(number, end=" ")
    number -= 1
print()